update ci.yml file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -18,7 +18,10 @@ jobs:
         with:
           go-version: '1.20'
 
-      - name: Force Failure
-        run: (exit 1)
+      # - name: Force Failure
+      #   run: (exit 1)
+
+      - name: Go version
+        run: go version
 
 #testing
